/**
 * Copy the "Built with tau" badge script into the Worker.
 *
 *   bun run sync-badge
 *
 * The badge lives at `server/src/lib/badge/badge.js` and is one script for the
 * preview and for published sites. The Worker cannot read the server's files at
 * run time, so its source is generated into `src/badgeSource.ts`. The root
 * drift test fails when the two differ, which is the reminder to run this.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dir, "..", "..");
const source = readFileSync(join(root, "server", "src", "lib", "badge", "badge.js"), "utf8");

writeFileSync(
  join(import.meta.dir, "..", "src", "badgeSource.ts"),
  `// Generated by scripts/sync-badge.ts from server/src/lib/badge/badge.js. Do not edit.\nexport const BADGE_SOURCE = ${JSON.stringify(source)};\n`,
);
console.log(`badgeSource.ts written (${source.length} characters)`);
