import { useState, type CSSProperties } from "react";

const CODE = [
  "export default function App() {",
  "  return (",
  '    <Nav brand="EMBER & OAK" cart={cart.count} />',
  "",
  "    <Hero",
  '      eyebrow="Est. 2019 · Lisbon"',
  '      title="Slow coffee, roasted on Fridays."',
  '      body="Small batches from three farms…"',
  "      actions={[",
  '        <Button tone="ember" onClick={order}>Order ahead</Button>,',
  '        <Button variant="outline" href="#menu">See the menu</Button>,',
  "      ]}",
  '      image={<Photo src="/hero.jpg" radius={18} />}',
  "    />",
  "",
  "    <MenuGrid>",
  "      {menu.map((item) => (",
  "        <MenuCard key={item.id} name={item.name} price={eur(item.price)} />",
  "      ))}",
  "    </MenuGrid>",
  "  );",
  "}",
  "",
  "// generated by tau · edit freely, push to GitHub",
];

export default function XRayLens() {
  const [full, setFull] = useState(false);
  const [point, setPoint] = useState({ x: 380, y: 210 });
  const line = Math.max(
    1,
    Math.min(CODE.length, Math.floor((point.y - 18) / 22) + 1),
  );

  return (
    <section id="x-ray" className="storm-band storm-container">
      <div className="xray-heading">
        <h2>
          Every pixel has
          <br />
          <span>a line behind it</span>
        </h2>
        <p>
          What tau builds is plain, readable code in your project, ready to edit
          in the workspace or push to GitHub.
        </p>
      </div>
      <div
        className={`xray-demo ${full ? "full" : ""}`}
        style={
          {
            "--lens-x": `${point.x}px`,
            "--lens-y": `${point.y}px`,
          } as CSSProperties
        }
        onPointerMove={(event) => {
          if (event.pointerType === "touch") return;
          const rect = event.currentTarget.getBoundingClientRect();
          setPoint({
            x: event.clientX - rect.left,
            y: event.clientY - rect.top,
          });
        }}
      >
        <div className="coffee-preview" aria-hidden={full}>
          <div className="coffee-nav">
            <strong>EMBER &amp; OAK</strong>
            <span>
              Menu　 Visit　 About　 <b>Cart · 2</b>
            </span>
          </div>
          <div className="coffee-hero">
            <div>
              <small>EST. 2019 · LISBON</small>
              <h3>
                Slow coffee,
                <br />
                roasted on Fridays.
              </h3>
              <p>Small batches from three farms we visit every year.</p>
              <div className="coffee-actions">
                <span>Order ahead</span>
                <span>See the menu</span>
              </div>
            </div>
            <div className="coffee-photo">hero photo</div>
          </div>
          <div className="coffee-menu">
            {[
              ["Flat white", "€3.20"],
              ["Cortado", "€2.80"],
              ["Cold brew", "€3.60"],
            ].map(([name, price]) => (
              <div key={name}>
                {name}
                <span>{price}</span>
              </div>
            ))}
          </div>
        </div>
        <div className="xray-code" aria-hidden={!full}>
          <pre>
            {CODE.map((text, index) => (
              <div
                key={index}
                className={line === index + 1 ? "current-line" : ""}
              >
                <span>{index + 1}</span>
                <code
                  style={{
                    color: text.startsWith("export")
                      ? "#c084fc"
                      : text.includes('="')
                        ? "#ffb27a"
                        : "#93c5fd",
                  }}
                >
                  {text || " "}
                </code>
              </div>
            ))}
          </pre>
        </div>
        {!full && (
          <div className="xray-ring" aria-hidden="true">
            <span>src/App.tsx · L{line}</span>
          </div>
        )}
        <button
          type="button"
          className="xray-toggle mono"
          aria-pressed={full}
          onClick={() => setFull(!full)}
        >
          {full ? "FULL X-RAY · CLICK TO CLOSE" : "CLICK FOR FULL X-RAY"}
        </button>
      </div>
      <p className="xray-help mono">
        Move over the preview to see the code underneath. Toggle full X-ray with
        the button.
      </p>
    </section>
  );
}
