-- AlterEnum
--
-- Runtime inference through the /v1 gateway, spent by a generated app rather
-- than by a build. Distinct from DEBIT so /billing and the admin views can
-- split "building" from "app usage" with a `where` instead of a string match.
--
-- reconcileAccount() sums every ledger row regardless of type, so the gross
-- invariant holds automatically. reconcileJob() filters on jobId, which these
-- rows do not carry, so it stays exactly as accurate as before.
--
-- Kept in its own migration: Postgres will not let a new enum value be USED in
-- the same transaction that adds it, which is why Prisma always emits enum
-- additions standalone (see 20260713130000_preview_job_type).
ALTER TYPE "LedgerType" ADD VALUE 'GATEWAY_DEBIT';
